# Como tratar as tabelas:

* Os dados de Cartão de Credito foram extraidos de dados abertos do Banco Central através do link abaixo:
>https://www.bcb.gov.br/estatisticas/spbadendos?ano=2024
* A planilha do Banco Central do Brasil normalmente vem em formato horizontal, por isso tivemos de tratar a tabela
* Tivemos tambem que excluir as colunas e linhas NaN
* Depois Salvamos o Dataset pronto

In [1]:
import pandas as pd

arquivo = "Dados Estatísticos 2024S1.xlsx"

df_qtd = pd.read_excel(arquivo, sheet_name="2.1.a")
df_valor = pd.read_excel(arquivo, sheet_name="2.1.b")

In [2]:
df_valor.head()

,2.1.b Cartões de Crédito - Transações no Exterior - por Arranjo de Pagamento (Quantidade),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Voltar ao Índice
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ano,Trimestre,Visa,Mastercard,American Express,Diners Club,Elo
2,2011,1º trimestre de 2011,11640137,7446671,1926721,185947,0
3,NaN,2º trimestre de 2011,11620375,7152273,1814600,157632,0
4,NaN,3º trimestre de 2011,13265028,8377856,1868871,148329,0

In [3]:
df_qtd.head()

,2.1.a Cartões de Crédito - Transações Domésticas - por Arranjo de Pagamento (Quantidade),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Voltar ao Índice,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ano,Trimestre,Visa,Mastercard,American Express,Diners Club,Hipercard,Bandeira própria1,Elo,Outros2
2,2011,1º trimestre de 2011,440565002,343937688,27697241,4288415,49117684,755425,56,1199813
3,NaN,2º trimestre de 2011,481055687,387031093,28618087,4232153,53801257,832956,39492,1885836
4,NaN,3º trimestre de 2011,500488736,395219189,30145358,4319832,51822202,879333,206100,1192717

In [4]:
# Transpor os dados
df_valor = df_valor.T

# Agora colunas viram linhas.

In [5]:
# Transformar a primeira linha em cabeçalho

df_valor.columns = df_valor.iloc[0]
df_valor = df_valor[1:]

In [6]:
# Transformar índice em coluna Ano

df_valor = df_valor.reset_index()
df_valor.rename(columns={"index": "Ano"}, inplace=True)

In [7]:
# remover colunas totalmente vazias
df_valor = df_valor.dropna(axis=1, how="all")

# pegar a linha que tem os dados
dados = df_valor.iloc[1]

# pegar os anos das colunas
anos = df_valor.columns

# criar novo dataframe
df_final = pd.DataFrame({
    "Ano": anos,
    "valorcartaocredito": dados.values
})

# remover linhas que não são anos
df_final = df_final[pd.to_numeric(df_final["Ano"], errors="coerce").notnull()]

# converter tipos
df_final["Ano"] = df_final["Ano"].astype(int)
df_final["valorcartaocredito"] = pd.to_numeric(df_final["valorcartaocredito"], errors="coerce")

display(df_final)

     Ano  valorcartaocredito
2   2011            11640137
6   2012            11599414
10  2013            12429519
14  2014            15965575
18  2015            14485437
22  2016            10122151
26  2017            12091440
30  2018            10376692
34  2019             9900344
38  2020             8665177
42  2021             3438457
46  2022             6301820
50  2023             8991563
54  2024            10868634

In [8]:
# Corrigindo o indice

df_final = df_final.reset_index(drop=True)

In [9]:
df_final

     Ano  valorcartaocredito
0   2011            11640137
1   2012            11599414
2   2013            12429519
3   2014            15965575
4   2015            14485437
5   2016            10122151
6   2017            12091440
7   2018            10376692
8   2019             9900344
9   2020             8665177
10  2021             3438457
11  2022             6301820
12  2023             8991563
13  2024            10868634

In [10]:
# Salvando

df_final.to_csv("valor_cartao_credito.csv", index=False)

---

In [11]:
# Transpor os dados
df_qtd = df_qtd.T

# Agora colunas viram linhas.

In [12]:
# Transformar a primeira linha em cabeçalho

df_qtd.columns = df_qtd.iloc[0]
df_qtd = df_qtd[1:]

In [13]:
# Transformar índice em coluna Ano

df_qtd = df_qtd.reset_index()
df_qtd.rename(columns={"index": "Ano"}, inplace=True)

In [14]:
# remover colunas totalmente vazias
df_qtd = df_qtd.dropna(axis=1, how="all")

# pegar a linha que tem os dados
dados = df_qtd.iloc[1]

# pegar os anos das colunas
anos = df_qtd.columns

# criar novo dataframe
df_final2 = pd.DataFrame({
    "Ano": anos,
    "NumeroTransacoesCartaoCredito": dados.values
})

# remover linhas que não são anos
df_final2 = df_final2[pd.to_numeric(df_final2["Ano"], errors="coerce").notnull()]

# converter tipos
df_final2["Ano"] = df_final2["Ano"].astype(int)
df_final2["NumeroTransacoesCartaoCredito"] = pd.to_numeric(df_final2["NumeroTransacoesCartaoCredito"], errors="coerce")

display(df_final2)

     Ano  NumeroTransacoesCartaoCredito
2   2011                      440565002
6   2012                      498398296
10  2013                      547092493
14  2014                      625848287
18  2015                      627450033
22  2016                      655815413
26  2017                      668975410
30  2018                      686111863
34  2019                      804390562
38  2020                      880413384
42  2021                      922487986
46  2022                     1350389113
50  2023                     1518810243
54  2024                     1621664074

In [15]:
df_final2 = df_final2.reset_index(drop=True)

In [16]:
df_final2

     Ano  NumeroTransacoesCartaoCredito
0   2011                      440565002
1   2012                      498398296
2   2013                      547092493
3   2014                      625848287
4   2015                      627450033
5   2016                      655815413
6   2017                      668975410
7   2018                      686111863
8   2019                      804390562
9   2020                      880413384
10  2021                      922487986
11  2022                     1350389113
12  2023                     1518810243
13  2024                     1621664074

In [17]:
df_final2.to_csv("Numero_Transacoes_Cartao_Credito.csv", index=False)