## `Análise de Vendas para uma Loja de E-commerce com Pandas e Numpy`

*Esse é um trabalho de análise de dados em Python.
Usando bibliotecas, como Pandas e NumPy, o projeto busca consolidar, limpar e explorar os registros de vendas, revelando padrões ocultos. O resultado esperado é fornecer insights acionáveis que permitam otimizar oportfólio de produtos, direcionar campanhas de marketing, antecipar tendências sazonais e guiar decisões de expansão regional, estabelecendo uma cultura de tomada de decisão orientada por dados.*

# **1. Definição do Problema de Negócio**

#### **1.1. O Problema de Negócio:**

Nossa loja de e-commerce está em fase de crescimento, registrando um volume cada vez maior de transações diárias. No entanto, essa grande quantidade de dados de vendas, em seu estado  bruto,  é  como  um  baú  de  tesouro  trancado:  sabemos  que  há  valor  ali,  mas  não conseguimos acessá-lo.

Atualmente,   muitas   de   nossas   decisões   estratégicas   são   baseadas   em   intuição   e observações parciais, o que nos leva a enfrentar os seguintes desafios:

**Gestão  de  Estoque  Ineficiente:**  
Não  temos  clareza  sobre  quais  produtos  são  nossos "campeões de venda" e quais estão parados nas prateleiras. Isso resulta em excesso de estoque de itens de baixa procura e falta de produtos de alta demanda.

**Marketing com Baixo Retorno:** 
Nossas campanhas de marketing são genéricas, pois não sabemos quais categorias de produtos atraem mais os clientes ou em quais regiões geográficas nosso público está mais concentrado.

**Perda de Oportunidades Sazonais:**
Não conseguimos identificar padrões ou tendências de vendas ao longo dos meses. Isso nos impede de planejar promoções estratégicas para períodos de alta ou de criar ações para impulsionar as vendas em meses de baixa.

**Expansão sem Direção:** 
Temos o desejo de expandir, mas não sabemos quais mercados regionais são mais promissores ou onde nossos esforços logísticos deveriam ser focados.

**O problema central é a falta de visibilidade clara sobre a performance do negócio, o que nos impede de tomar decisões rápidas, inteligentes e baseadas em evidências.**

#### **1.3. Solução Proposta**

*A  solução  consiste  em  consolidar,  limpar  e  analisar  o  histórico  de  dados  de  vendas  da nossa plataforma. Utilizando ferramentas de análise de dados (como Python com Pandas, NumPy),  vamos  processar  essas  informações e  criar  um  relatório que  apresente  as descobertas de forma clara e intuitiva para as equipes de gestão, marketing e operações*

#### **1.4. Resultados Esperados e Benefícios de Negócio**

Ao final deste projeto, esperamos alcançar os seguintes resultados:

**1. Otimização  de  Estoque:**  Com  a  lista  dos  produtos  mais  e  menos  vendidos,  poderemos ajustar nossas compras, reduzir custos com armazenamento e evitar a perda de vendas por falta de produto.

**2. Marketing Direcionado e Eficaz:** Sabendo quais categorias e regiões são mais lucrativas, a equipe  de  marketing  poderá  criar  campanhas  3. segmentadas,  aumentando  o  retorno  sobre  o investimento (ROI).

**3. Planejamento  Estratégico:**  A  visualização  das  tendências  mensais  permitirá  um  melhor planejamento  financeiro,  promocional  e  de  recursos,  antecipando  períodos  de  alta  e  baixa demanda.

**4. Decisões  Baseadas  em  Dados:**  Substituiremos  a  intuição  por  dados  concretos,  criando uma cultura orientada a dados que impulsionará o crescimento sustentável do negócio.

# 2. Importando Bibliotecas

In [1]:
import pandas as pd

import numpy as np

from datetime import datetime, timedelta

# 3. Carregar Dados

In [2]:
caminho = 'dados_vendas_com_data.xlsx'

In [3]:
df = pd.read_excel(caminho, parse_dates=["Data_Pedido"])

In [4]:
print(df.dtypes)

ID_Pedido                  int64
Data_Pedido       datetime64[ns]
Nome_Produto              object
Categoria                 object
Preco_Unitario           float64
Quantidade                 int64
ID_Cliente                 int64
Cidade                    object
Estado                    object
dtype: object

# 4. Explorar os Dados

In [5]:
df_vendas = df

In [6]:
df_vendas.shape

# 500 registros(linhas) para 9 colunas

(500, 9)

In [7]:
df_vendas.head()

# Verificando as 5 primeiras linhas

,ID_Pedido,Data_Pedido,Nome_Produto,Categoria,Preco_Unitario,Quantidade,ID_Cliente,Cidade,Estado
0,1000,2026-01-01 10:00:00,Laptop Gamer,Eletrônicos,7500.00,1,123,Curitiba,PR
1,1001,2026-01-01 12:00:00,Mouse Vertical,Acessórios,239.06,4,108,Belo Horizonte,MG
2,1002,2026-01-01 22:00:00,Headset 7.1,Acessórios,800.00,6,134,Salvador,BA
3,1003,2026-01-01 21:00:00,Placa de Vídeo,Hardware,4500.00,2,147,Porto Alegre,RS
4,1004,2026-01-01 05:00:00,SSD 1TB,Hardware,600.00,7,117,Salvador,BA

In [8]:
df_vendas.info()

# Exibindo informações gerais sobre o dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Pedido       500 non-null    int64
 1   Data_Pedido     500 non-null    datetime64[ns]
 2   Nome_Produto    500 non-null    object
 3   Categoria       500 non-null    object
 4   Preco_Unitario  500 non-null    float64
 5   Quantidade      500 non-null    int64
 6   ID_Cliente      500 non-null    int64
 7   Cidade          500 non-null    object
 8   Estado          500 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(3), object(4)
memory usage: 35.3+ KB

In [9]:
df_vendas.describe()

# Resumo Estatistico

,ID_Pedido,Data_Pedido,Preco_Unitario,Quantidade,ID_Cliente
count,500.000000,500,500.000000,500.000000,500.000000
mean,1249.500000,2026-02-19 23:33:07.200000,2260.218360,4.158000,124.680000
min,1000.000000,2026-01-01 05:00:00,225.490000,1.000000,100.000000
25%,1124.750000,2026-01-26 00:45:00,542.105000,3.000000,113.000000
50%,1249.500000,2026-02-19 23:30:00,800.000000,4.000000,125.000000
75%,1374.250000,2026-03-16 22:30:00,4500.000000,6.000000,136.000000
max,1499.000000,2026-04-10 18:00:00,7500.000000,7.000000,149.000000
std,144.481833,NaN,2442.967901,1.920524,14.036654

# 5. Limpeza, Pré-processamento e Eng. de Atributos

In [10]:
# Se a coluna 'Data_Pedido' não estiver como tipo datetime, precisamos fazer a conversão
# A coluna pode ser usada para análise temporal

df_vendas['Data_Pedido'] = pd.to_datetime(df_vendas['Data_Pedido'])

In [11]:
# Engenharia de atributos
# Criando a coluna 'Faturamento' (preço x quantidade)

df_vendas['Faturamento'] = df_vendas['Preco_Unitario'] * df_vendas['Quantidade']

In [12]:
# Engenharia de atributos
# Usando uma função lambda para criar uma coluna de status de entrega
# Se a estrega for no Estados de SP, RJ, MG será rapida

df_vendas['Status_Entrega'] = df_vendas['Estado'].apply(lambda estado: 'Rápida' if estado in ['SP', 'RJ', 'MG'] else 'Normal')

In [13]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Pedido       500 non-null    int64
 1   Data_Pedido     500 non-null    datetime64[ns]
 2   Nome_Produto    500 non-null    object
 3   Categoria       500 non-null    object
 4   Preco_Unitario  500 non-null    float64
 5   Quantidade      500 non-null    int64
 6   ID_Cliente      500 non-null    int64
 7   Cidade          500 non-null    object
 8   Estado          500 non-null    object
 9   Faturamento     500 non-null    float64
 10  Status_Entrega  500 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(3), object(5)
memory usage: 43.1+ KB

In [14]:
df_vendas.head()

,ID_Pedido,Data_Pedido,Nome_Produto,Categoria,Preco_Unitario,Quantidade,ID_Cliente,Cidade,Estado,Faturamento,Status_Entrega
0,1000,2026-01-01 10:00:00,Laptop Gamer,Eletrônicos,7500.00,1,123,Curitiba,PR,7500.00,Normal
1,1001,2026-01-01 12:00:00,Mouse Vertical,Acessórios,239.06,4,108,Belo Horizonte,MG,956.24,Rápida
2,1002,2026-01-01 22:00:00,Headset 7.1,Acessórios,800.00,6,134,Salvador,BA,4800.00,Normal
3,1003,2026-01-01 21:00:00,Placa de Vídeo,Hardware,4500.00,2,147,Porto Alegre,RS,9000.00,Normal
4,1004,2026-01-01 05:00:00,SSD 1TB,Hardware,600.00,7,117,Salvador,BA,4200.00,Normal

# 6. Análise 1 - Top 10 produtos mais vendidos

In [15]:
# Agrupa por nome do produto, soma a quantidade e ordena para encontrar os mais vendidos

top_10_produtos = df_vendas.groupby('Nome_Produto')['Quantidade'].sum().sort_values(ascending = False).head(10)

In [16]:
top_10_produtos

Nome_Produto
Mouse Vertical       303
Laptop Gamer         286
Headset 7.1          272
Cadeira Gamer        270
SSD 1TB              254
Placa de Vídeo       252
Teclado Mecânico     247
Monitor Ultrawide    195
Name: Quantidade, dtype: int64

# 7. Analise 2 - Faturamento Mensal

**Qual foi o faturamento mensal?**

In [17]:
df_vendas.head()

,ID_Pedido,Data_Pedido,Nome_Produto,Categoria,Preco_Unitario,Quantidade,ID_Cliente,Cidade,Estado,Faturamento,Status_Entrega
0,1000,2026-01-01 10:00:00,Laptop Gamer,Eletrônicos,7500.00,1,123,Curitiba,PR,7500.00,Normal
1,1001,2026-01-01 12:00:00,Mouse Vertical,Acessórios,239.06,4,108,Belo Horizonte,MG,956.24,Rápida
2,1002,2026-01-01 22:00:00,Headset 7.1,Acessórios,800.00,6,134,Salvador,BA,4800.00,Normal
3,1003,2026-01-01 21:00:00,Placa de Vídeo,Hardware,4500.00,2,147,Porto Alegre,RS,9000.00,Normal
4,1004,2026-01-01 05:00:00,SSD 1TB,Hardware,600.00,7,117,Salvador,BA,4200.00,Normal

In [18]:
# Cria uma coluna 'Mes' para facilitar o agrupamento mensal
df_vendas['Mes'] = df_vendas['Data_Pedido'].dt.to_period('M')

In [19]:
df_vendas.head(10)

,ID_Pedido,Data_Pedido,Nome_Produto,Categoria,Preco_Unitario,Quantidade,ID_Cliente,Cidade,Estado,Faturamento,Status_Entrega,Mes
0,1000,2026-01-01 10:00:00,Laptop Gamer,Eletrônicos,7500.00,1,123,Curitiba,PR,7500.00,Normal,2026-01
1,1001,2026-01-01 12:00:00,Mouse Vertical,Acessórios,239.06,4,108,Belo Horizonte,MG,956.24,Rápida,2026-01
2,1002,2026-01-01 22:00:00,Headset 7.1,Acessórios,800.00,6,134,Salvador,BA,4800.00,Normal,2026-01
3,1003,2026-01-01 21:00:00,Placa de Vídeo,Hardware,4500.00,2,147,Porto Alegre,RS,9000.00,Normal,2026-01
4,1004,2026-01-01 05:00:00,SSD 1TB,Hardware,600.00,7,117,Salvador,BA,4200.00,Normal,2026-01
5,1005,2026-01-02 01:00:00,Cadeira Gamer,Móveis,1200.00,6,131,Rio de Janeiro,RJ,7200.00,Rápida,2026-01
6,1006,2026-01-02 13:00:00,SSD 1TB,Hardware,600.00,3,145,Rio de Janeiro,RJ,1800.00,Rápida,2026-01
7,1007,2026-01-02 02:00:00,Laptop Gamer,Eletrônicos,7500.00,4,113,Curitiba,PR,30000.00,Normal,2026-01
8,1008,2026-01-02 12:00:00,Cadeira Gamer,Móveis,1200.00,5,120,Curitiba,PR,6000.00,Normal,2026-01
9,1009,2026-01-02 13:00:00,Mouse Vertical,Acessórios,249.64,3,104,Rio de Janeiro,RJ,748.92,Rápida,2026-01

In [20]:
# Agrupa por mês e soma o faturamento
faturamento_mensal = df_vendas.groupby('Mes')['Faturamento'].sum()

In [21]:
# Converte o índice para string para facilitar a plotagem no gráfico
faturamento_mensal.index = faturamento_mensal.index.strftime('%Y-%m')

In [22]:
# Formata para duas casas decimais
faturamento_mensal.map('R$ {:,.2f}'.format)

Mes
2026-01    R$ 1,366,408.29
2026-02    R$ 1,296,961.89
2026-03    R$ 1,514,509.05
2026-04      R$ 542,449.24
Name: Faturamento, dtype: object

## 8. Análise 3 - Vendas Por Estado

**Qual o total de vendas por estado?**

In [23]:
# Agrupa por estado e soma o faturamento
vendas_estado = df_vendas.groupby('Estado')['Faturamento'].sum().sort_values(ascending = False)

In [24]:
# Formata para duas casas decimais
vendas_estado.map('R$ {:,.2f}'.format)

Estado
RJ    R$ 789,472.30
PR    R$ 763,360.72
SP    R$ 724,681.02
MG    R$ 622,186.50
CE    R$ 622,029.26
RS    R$ 619,839.65
BA    R$ 578,759.02
Name: Faturamento, dtype: object

## 9. Análise 4 - Faturamento Por Categoria

**Qual o faturamento total por categoria?**

In [25]:
# Agrupa por categoria, soma o faturamento e formata como moeda para melhor leitura
faturamento_categoria = df_vendas.groupby('Categoria')['Faturamento'].sum().sort_values(ascending = False)

In [26]:
# O .map('{:,.2f}'.format) é opcional, mas deixa a visualização do número mais clara
faturamento_categoria.map('R$ {:,.2f}'.format)

Categoria
Eletrônicos    R$ 2,691,000.00
Hardware       R$ 1,286,400.00
Acessórios       R$ 418,928.47
Móveis           R$ 324,000.00
Name: Faturamento, dtype: object

## 10. Conclusão e Entrega do Resultado

Existem várias formas de entregar um projeto de análise de dados e a escolha depende do público, do contexto e dos objetivos. Três formas bastante utilizadas são:

**10.1. Relatório técnico ou executivo (PDF, DOCX, etc.)**

Essa forma é clássica e muito útil quando o público precisa de um documento formal para consulta. O relatório pode conter descrição da metodologia, exploração dos dados, gráficos, tabelas e conclusões.

**10.2. Dashboard interativo (Power BI, Tableau, Looker, Dash, etc.)**

Um dashboard permite que os usuários explorem os dados por conta própria, filtrando informações, ajustando períodos de tempo ou focando em variáveis específicas. Essa forma de entrega é muito valorizada em ambientes corporativos, pois facilita a tomada de decisão contínua e não exige conhecimentos técnicos avançados dos usuários finais.

**10.3. Apresentação (slides em PowerPoint, Google Slides, etc.)**

Ideal para reuniões, a entrega em formato de apresentação resume os principais pontos do projeto. Ela foca nas descobertas mais relevantes, nas implicações para o negócio e nas recomendações práticas, usando gráficos e visualizações impactantes. A ideia é contar a história dos dados de forma clara e direta, evitando sobrecarregar o público com detalhes técnicos.

# Fim